# data store
---
variable name: database
use object: True
data: 
  - service name: Anglicare The Magdalene Centre
    phone: 83059434
    location: 82 Gilbert St, Adelaide SA 5000, Australia
    website: https://anglicaresa.com.au
    # open hours:
    # indigenous: False
  - service name: Australian Migrant Resource Centre (AMRC)
    phone: 08 8217 9500
    location: 23 Coglin St, Adelaide SA 5000, Australia
    website: https://amrc.org.au
    # indigenous: True
  - service name: Nunkuwarrin Yunti
    phone: (08) 8406 1600
    location: 182 Wakefield St, Adelaide SA 5000, Australia
    website: reception@nunku.org.au
    # indigenous: False
---