# this is a placeholder template I've got from the second workshop.
# We can modify it to either store all our information or
# redirect to external data store.
---
variable name: database
use object: True
data: 
  - service name: Brownwell House
    phone: 1000 000 000
    website: https://brownellhouse.org
    indigenous: False
  - service name: Kurlana Tarpawa
    phone: 2000 000 000
    website: https://dhs.sa.gov.au/how-we-help/youth-justice/youth-justice-services/kurlana-tapa-youth-justice-centre
    indigenous: True
  - service name: Foyer Port Adelaide
    phone: 3000 000 000
    website: https://www.stjohnsyouthservices.org.au/services/foyer-port-adelaide/
    indigenous: False
---